use rs2ty::{AsTyExt, RecognizedResult, Recognizer, tsty::TsType};
use std::fs::File;
use std::io::Write;

const AUTO_GENERATE: &str = r#"// this file is auto generated by rs2ty, please do not modify it manually.

declare global {
  interface Window {
    $wujie?: {  props?: {   pluginId?: string;  }   };
    bridge: {
      send<T = any>(action: string, payload?: any): Promise<T>;
    };
  }
}
    
"#;

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    run("fun", "./src/lib.rs", "./src/shared/bridge.ts").unwrap();
}

fn run(name: &str, from: &str, to: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut recognizer = Recognizer::new(&[name])?;
    recognizer.add_all([from])?;
    let result = &recognizer.recognize()?;
    let mut result: RecognizedResult<TsType> = result.asty();

    let mut file = File::create(to)?;

    writeln!(&mut file, "{AUTO_GENERATE}")?;

    writeln!(
        &mut file,
        "const pluginid = window.$wujie?.props?.pluginId;\n"
    )?;

    // 输出所有接口/类型定义
    for (k, v) in result.tys {
        match &v {
            TsType::Object(e) if !e.is_empty() => {
                writeln!(&mut file, "export interface {k} {v};")?;
            }
            TsType::Enum(e) if !e.is_empty() => {
                writeln!(&mut file, "export type {k} = {v};")?;
            }
            _ => {}
        }
    }

    // 生成 command 对象，收集每个方法
    writeln!(&mut file, "\nexport const Command = {{")?;

    for fninfo in result.fns.iter_mut() {
        // 过滤掉 WindowState 参数（同原逻辑）
        let args = &fninfo.args;
        let new_args = args
            .iter()
            .filter(|(_, t)| match t {
                TsType::Name(name) => name != "WindowState",
                _ => true,
            })
            .cloned()
            .collect::<Vec<_>>();
        fninfo.args = new_args;

        // 生成方法体：直接调用 window.bridge.send
        let method_body = format!(
            "window.parent.bridge.send<{}>('callplugin', {{ pluginid, 'method': '{}', 'params': {{ {} }} }})",
            fninfo.ret,
            fninfo.name,
            fninfo
                .args
                .iter()
                .map(|(name, _)| name.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );

        // 生成参数列表字符串
        let params_str = fninfo
            .args
            .iter()
            .map(|(name, ty)| format!("{name}: {ty}"))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            &mut file,
            "  {}: ({}) => {},",
            fninfo.name, params_str, method_body
        )?;
    }

    writeln!(&mut file, "}};")?;

    Ok(())
}
