[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
plugin = { git = "https://github.com/munch1182/START.git", branch = "master", package = "plugin" }
marker = { git = "https://github.com/munch1182/p2.git", branch = "dev", package = "marker" }

[build-dependencies]
rs2ty = { git = "https://github.com/munch1182/p2.git", branch = "dev", package = "rs2ty", features = [
    "ts",
] }
